-- Q1 What is the total revenue generated by the male and female customer ?
select gender, sum("purchase_amount_(usd)") as revenue_generated
from customer 
group by gender

---------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- Q2 How many customer used a discount but still spent more than the average purchase amount ?
select count(customer_id) as Customer_count from customer where discount_applied='Yes' 
and 
[purchase_amount_(usd)] > (select AVG("purchase_amount_(usd)") from customer)

----------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- Q3 Which are the top 5 products with the highest average review rating ?
select top 5 item_purchased as Top_product , round(avg(review_rating), 2) as Review_Rating from customer 
group by item_purchased
order by Review_Rating desc

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- Q4 Compare the average purchase amounts between standard and express shipping ?
select shipping_type, avg("purchase_amount_(usd)") as Purchased_amount from customer
where shipping_type in('Express', 'Standard')
group by shipping_type 


-- Q5 Do subscribed customer spend more? compare the average spend and total revenue generated between subscribers and non subscribers.
select subscription_status , avg("purchase_amount_(usd)") as average_spending, sum("purchase_amount_(usd)") as Total_revenue from customer
group by subscription_status


-- Q6 Which 5 products have highest percentage of purchase with discount applied.
SELECT TOP 5
item_purchased,Round((SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)), 2) AS Discount_Percentage
FROM customer
GROUP BY item_purchased
ORDER BY Discount_Percentage DESC;

--------------------------------------------------------------------------------------------------------------------------------------------

-- Q7 Segment customer into New, Returning and Loyal based on their total number of previous purchases and show the count segment.

select max(previous_purchases), min(previous_purchases), AVG(previous_purchases) from customer

with segment_customer as (
select customer_id, previous_purchases,
case when  previous_purchases between 1 and 10 then 'New'
when previous_purchases between 11 and 30 then 'Returning'
else 'Loyal'
end as Segment 
from customer
)
select segment, count(segment) As customer_count from segment_customer 
group by segment 
order by segment desc

--------------------------------------------------------------------------------------------------------------------------------------------------------

--Q8 What are the Top 3 most purchased products with in each category?
select * from
(
    SELECT
        category,
        item_purchased,
        COUNT(item_purchased) AS purchased_count,
        DENSE_RANK() OVER (
            PARTITION BY category
            ORDER BY COUNT(item_purchased) DESC
        ) AS purchased_rank
    FROM customer
    GROUP BY category, item_purchased
)t where purchased_rank < 4;

-----------------------------------------------------------------------------------------------------------------------------------
-- Q9 Are customers who are repeat buyers (more than 5 previous purchases) are likely to subscribe
select subscription_status, count(customer_id) as repeat_buyers
from customer 
where previous_purchases>5
group by subscription_status

--Q10 What is the revenue contribution of each age group?
select * from customer
select age_group,
sum("purchase_amount_(usd)") as total_revenue
from customer
group by age_group
order by total_revenue desc


